# Generated by Django 3.1.6 on 2022-06-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220613_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='verified',
            new_name='verified_student',
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='media/default.jpeg', upload_to='users/%Y/%m/%d/'),
        ),
    ]
