# Generated by Django 3.1.6 on 2022-06-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220613_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='media/default.jpeg', upload_to='users/%Y/%m/%d/'),
        ),
    ]
