# Generated by Django 3.1.6 on 2022-06-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_photo_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
